spring.application.name=aiassistant

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/ai_assistant
spring.datasource.username=root
spring.datasource.password=Code2028

#gemini.api.key=${GEMINI_API_KEY}

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

cloudinary.cloud-name=dxxfcxtks
cloudinary.api-key=772479616591163
cloudinary.api-secret=XfR4LwG6cOkJRXUOJIYOZTSkxdQ
cloudinary.folder-name=ai_assistant_uploads

spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.project-id=com.subhajit.aiassistant
spring.ai.google.genai.embedding.text.model=text-embedding-004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
