spring.application.name=aiassistant

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/ai_assistant
spring.datasource.username=root
spring.datasource.password=Code2028

#gemini.api.key=${GEMINI_API_KEY}

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
